import { watch } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import { formatHex } from "culori";

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const packageDirectory = path.resolve(scriptDirectory, "..");
const themeCssPath = path.join(packageDirectory, "theme.css");
const outputPath = path.join(packageDirectory, "theme.ts");
const generatedHeader =
  "// This file is generated by scripts/generate-theme.ts. Do not edit manually.\n";

type ThemeMode = "light" | "dark";
type ThemeColors = Record<string, string>;

function extractBlock(css: string, selector: string): string {
  const startIndex = css.indexOf(selector);

  if (startIndex === -1) {
    throw new Error(`Missing ${selector} block in theme.css`);
  }

  const openBraceIndex = css.indexOf("{", startIndex);

  if (openBraceIndex === -1) {
    throw new Error(`Missing opening brace for ${selector} block in theme.css`);
  }

  let depth = 0;

  for (let index = openBraceIndex; index < css.length; index += 1) {
    const character = css[index];

    if (character === "{") {
      depth += 1;
    }

    if (character === "}") {
      depth -= 1;

      if (depth === 0) {
        return css.slice(openBraceIndex + 1, index);
      }
    }
  }

  throw new Error(`Missing closing brace for ${selector} block in theme.css`);
}

function parseColors(block: string): ThemeColors {
  const colors: ThemeColors = {};

  for (const line of block.split("\n")) {
    const declaration = line.trim();

    if (!declaration.startsWith("--") || !declaration.endsWith(";")) {
      continue;
    }

    const separatorIndex = declaration.indexOf(":");

    if (separatorIndex === -1) {
      continue;
    }

    const token = declaration.slice(2, separatorIndex).trim();
    const rawValue = declaration.slice(separatorIndex + 1, -1).trim();

    if (!token || !rawValue) {
      continue;
    }

    const hex = formatHex(rawValue.trim());

    if (!hex) {
      continue;
    }

    colors[token] = hex;
  }

  return colors;
}

function serializeColors(mode: ThemeMode, colors: ThemeColors): string {
  const lines = Object.entries(colors).map(
    ([token, value]) =>
      `    ${JSON.stringify(token)}: ${JSON.stringify(value)},`,
  );

  return `  ${mode}: {\n${lines.join("\n")}\n  },`;
}

async function generateTheme(): Promise<void> {
  const css = await readFile(themeCssPath, "utf8");
  const lightColors = parseColors(extractBlock(css, ":root"));
  const darkColors = parseColors(extractBlock(css, ".dark"));
  const contents = `${generatedHeader}\nexport const theme = {\n${serializeColors("light", lightColors)}\n${serializeColors("dark", darkColors)}\n} as const;\n`;

  await writeFile(outputPath, contents, "utf8");
}

let pendingRun: Promise<void> | null = null;
let rerunRequested = false;

function queueGenerate(): void {
  if (pendingRun) {
    rerunRequested = true;
    return;
  }

  pendingRun = generateTheme()
    .then(() => {
      console.log(`Generated ${path.relative(packageDirectory, outputPath)}`);
    })
    .catch((error: unknown) => {
      console.error(error);
      process.exitCode = 1;
    })
    .finally(() => {
      pendingRun = null;

      if (rerunRequested) {
        rerunRequested = false;
        queueGenerate();
      }
    });
}

function watchTheme(): void {
  queueGenerate();

  const watcher = watch(themeCssPath, { persistent: true }, () => {
    // File watchers can emit multiple events per save, so serialize reruns.
    setTimeout(() => {
      queueGenerate();
    }, 25);
  });

  const stopWatching = (): void => {
    watcher.close();
    process.exit();
  };

  process.on("SIGINT", stopWatching);
  process.on("SIGTERM", stopWatching);
}

const shouldWatch = process.argv.includes("--watch");

if (shouldWatch) {
  watchTheme();
} else {
  await generateTheme();
  console.log(`Generated ${path.relative(packageDirectory, outputPath)}`);
}
